# Generated by Django 3.0.3 on 2020-02-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AcqItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=200)),
                ('iprice', models.FloatField(null=True)),
                ('idescription', models.CharField(max_length=3000, null=True)),
                ('itype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ItemType')),
            ],
        ),
    ]
